JWT::JwtValidator
readonly IJsonSerializer JWT.JwtValidator._jsonSerializer
readonly IDateTimeProvider JWT.JwtValidator._dateTimeProvider
readonly IBase64UrlEncoder JWT.JwtValidator._urlEncoder
readonly ValidationParameters JWT.JwtValidator._valParams
JWT.JwtValidator.JwtValidator(IJsonSerializer jsonSerializer, IDateTimeProvider dateTimeProvider)
Creates an instance of JwtValidator
jsonSerializer The JSON serializer dateTimeProvider The DateTime provider
JWT.JwtValidator.JwtValidator(IJsonSerializer jsonSerializer, IDateTimeProvider dateTimeProvider, ValidationParameters valParams)
Creates an instance of JwtValidator with time margin.
jsonSerializer The JSON serializer dateTimeProvider The DateTime provider valParams Validation parameters that are passed on to JwtValidator
JWT.JwtValidator.JwtValidator(IJsonSerializer jsonSerializer, IDateTimeProvider dateTimeProvider, ValidationParameters valParams, IBase64UrlEncoder urlEncoder)
Creates an instance of JwtValidator with time margin.
jsonSerializer The JSON serializer dateTimeProvider The DateTime provider valParams Validation parameters that are passed on to JwtValidator urlEncoder The base64 URL Encoder
void JWT.JwtValidator.Validate(string decodedPayload, string signature, params string[] decodedSignatures)
Given the JWT, verifies its signature correctness. decodedPayload >An arbitrary payload (already serialized to JSON) signature Decoded body decodedSignatures The signatures to validate with ArgumentException SignatureVerificationException
References JWT.JwtValidator.GetValidationException.
void JWT.JwtValidator.Validate(string decodedPayload, IAsymmetricAlgorithm alg, byte[] bytesToSign, byte[] decodedSignature)
Given the JWT, verifies its signature correctness. Used by the asymmetric algorithms only. ArgumentException SignatureVerificationException
References JWT.JwtValidator.GetValidationException.
bool JWT.JwtValidator.TryValidate(string payloadJson, string signature, string decodedSignature, out Exception ex)
Given the JWT, verifies its signature correctness without throwing an exception but returning it instead. payloadJson >An arbitrary payload (already serialized to JSON) signature Decoded body decodedSignature The signature to validate with ex The resulting validation exception, if any Returns true if exception is JWT is valid and exception is null, otherwise false ArgumentException
References JWT.JwtValidator.GetValidationException.
bool JWT.JwtValidator.TryValidate(string payloadJson, string signature, string[] decodedSignature, out Exception ex)
Given the JWT, verifies its signature correctness without throwing an exception but returning it instead. payloadJson >An arbitrary payload (already serialized to JSON) signature Decoded body decodedSignature The signatures to validate with ex The resulting validation exception, if any Returns true if exception is JWT is valid and exception is null, otherwise false ArgumentException
References JWT.JwtValidator.GetValidationException.
bool JWT.JwtValidator.TryValidate(string payloadJson, IAsymmetricAlgorithm alg, byte[] bytesToSign, byte[] decodedSignature, out Exception ex)
Given the JWT, verifies its signatures correctness without throwing an exception but returning it instead. payloadJson >An arbitrary payload (already serialized to JSON) alg The asymmetric algorithm to validate with bytesToSign The header and payload bytes to validate decodedSignature The decodedSignatures to validate with ex Validation exception, if any True if exception is JWT is valid and exception is null, otherwise false ArgumentException
References JWT.JwtValidator.GetValidationException.
Exception JWT.JwtValidator.GetValidationException(JwtParts parts)
References JWT.JwtValidator.GetValidationException, JWT.JwtParts.Payload.
Referenced by JWT.JwtValidator.GetValidationException, JWT.JwtValidator.GetValidationException, JWT.JwtValidator.TryValidate, JWT.JwtValidator.TryValidate, JWT.JwtValidator.TryValidate, JWT.JwtValidator.Validate, JWT.JwtValidator.Validate.
Exception JWT.JwtValidator.GetValidationException(byte[] bytes)
References JWT.JwtValidator.GetValidationException.
Exception JWT.JwtValidator.GetValidationException(string payloadJson, string decodedCrypto, params string[] decodedSignatures)
Exception JWT.JwtValidator.GetValidationException(IAsymmetricAlgorithm alg, string payloadJson, byte[] bytesToSign, byte[] decodedSignature)
Exception JWT.JwtValidator.GetValidationException(string payloadJson)
Exception JWT.JwtValidator.ValidateExpClaim(IReadOnlyPayloadDictionary payloadData, double secondsSinceEpoch)
Verifies the 'exp' claim.
See https://tools.ietf.org/html/rfc7519#section-4.1.4 SignatureVerificationException TokenExpiredException
Exception JWT.JwtValidator.ValidateNbfClaim(IReadOnlyPayloadDictionary payloadData, double secondsSinceEpoch)
Verifies the 'nbf' claim.
See https://tools.ietf.org/html/rfc7519#section-4.1.5 SignatureVerificationException
static bool JWT.JwtValidator.AreAllDecodedSignaturesNullOrWhiteSpace(string[] decodedSignatures)
static bool JWT.JwtValidator.IsAnySignatureValid(string decodedCrypto, string[] decodedSignatures)
static bool JWT.JwtValidator.CompareCryptoWithSignature(string decodedCrypto, string decodedSignature)
In the future this method can be opened for extension hence made protected virtual