JWT::Algorithms::CertificateAlgorithm
readonly T JWT.Algorithms.CertificateAlgorithm< T >._publicKey
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm, JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm, JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm.
readonly T JWT.Algorithms.CertificateAlgorithm< T >._privateKey
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm, JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm, JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm, JWT.Algorithms.CertificateAlgorithm< T >.Sign.
abstract string JWT.Algorithms.CertificateAlgorithm< T >.Name
Gets algorithm name.
abstract HashAlgorithmName JWT.Algorithms.CertificateAlgorithm< T >.HashAlgorithmName
Gets name of the hashing algorithm (e.g. SHA-256/SHA-384/SHA-512).
JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm(T publicKey, T privateKey)
References JWT.Algorithms.CertificateAlgorithm< T >._privateKey, JWT.Algorithms.CertificateAlgorithm< T >._publicKey.
JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm(T publicKey)
References JWT.Algorithms.CertificateAlgorithm< T >._privateKey, JWT.Algorithms.CertificateAlgorithm< T >._publicKey.
JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm(X509Certificate2 cert)
References JWT.Algorithms.CertificateAlgorithm< T >._privateKey, JWT.Algorithms.CertificateAlgorithm< T >._publicKey, JWT.Algorithms.CertificateAlgorithm< T >.GetPrivateKey, JWT.Algorithms.CertificateAlgorithm< T >.GetPublicKey.
abstract T JWT.Algorithms.CertificateAlgorithm< T >.GetPublicKey(X509Certificate2 cert)
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm.
abstract T JWT.Algorithms.CertificateAlgorithm< T >.GetPrivateKey(X509Certificate2 cert)
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.CertificateAlgorithm.
abstract byte[] JWT.Algorithms.CertificateAlgorithm< T >.SignData(byte[] bytesToSign)
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.Sign.
abstract bool JWT.Algorithms.CertificateAlgorithm< T >.VerifyData(byte[] bytesToSign, byte[] signature)
Referenced by JWT.Algorithms.CertificateAlgorithm< T >.Verify.
byte[] JWT.Algorithms.CertificateAlgorithm< T >.Sign(byte[] key, byte[] bytesToSign)
Signs provided byte array with provided key. key The key used to sign the data bytesToSign The data to sign
byte[] JWT.Algorithms.CertificateAlgorithm< T >.Sign(byte[] bytesToSign)
Signs the provided byte array with the private key.
References JWT.Algorithms.CertificateAlgorithm< T >._privateKey, JWT.Algorithms.CertificateAlgorithm< T >.SignData.
bool JWT.Algorithms.CertificateAlgorithm< T >.Verify(byte[] bytesToSign, byte[] signature)
Verifies provided byte array with provided signature. bytesToSign The data to verify signature The signature to verify with
References JWT.Algorithms.CertificateAlgorithm< T >.VerifyData.