Openlabs::Mgcxm::Common::Framework::EndpointResolver
EndpointFrameworkBase Openlabs.Mgcxm.Common.Framework.EndpointResolver.EndpointFramework
MgcxmHttpListener Openlabs.Mgcxm.Common.Framework.EndpointResolver.HttpListener
Referenced by Openlabs.Mgcxm.Common.Framework.EndpointResolver.EndpointResolver, Openlabs.Mgcxm.Common.Framework.OpenApiEndpointResolver.ResolveAll.
abstract IReadOnlyList<EndpointSubpartController> Openlabs.Mgcxm.Common.Framework.EndpointResolver.EndpointSubpartControllers
Openlabs.Mgcxm.Common.Framework.EndpointResolver.EndpointResolver(MgcxmHttpListener listener, EndpointFrameworkBase endpointFramework)
References Openlabs.Mgcxm.Common.Framework.EndpointResolver.HttpListener.
abstract MgcxmHttpEndpoint Openlabs.Mgcxm.Common.Framework.EndpointResolver.ResolveUrl(string url, MgcxmHttpRequest request)
Referenced by Openlabs.Mgcxm.Common.Framework.OpenApiFramework.ResolveRequest.
abstract void Openlabs.Mgcxm.Common.Framework.EndpointResolver.ResolveAll()
Referenced by Openlabs.Mgcxm.Tests.TestServer.TestServer.
abstract void Openlabs.Mgcxm.Common.Framework.EndpointResolver.AddSubpartController(EndpointSubpartController subpartController)
Referenced by Openlabs.Mgcxm.Tests.TestServer.TestServer.