Openlabs::Mgcxm::Assets::FileAsset
string Openlabs.Mgcxm.Assets.FileAsset.FileName
string Openlabs.Mgcxm.Assets.FileAsset.Extension
string Openlabs.Mgcxm.Assets.FileAsset.Path
string Openlabs.Mgcxm.Assets.FileAsset.Guid
Referenced by Openlabs.Mgcxm.Assets.JsonFileAsset.ReadObject< T >.
string Openlabs.Mgcxm.Assets.FileAsset._fileName
string Openlabs.Mgcxm.Assets.FileAsset._extension
string Openlabs.Mgcxm.Assets.FileAsset._path
string Openlabs.Mgcxm.Assets.FileAsset._guid
override async Task Openlabs.Mgcxm.Assets.FileAsset.Load(object[] arguments)
Referenced by Openlabs.Mgcxm.Tests.TestServer.MessagesController.Initialize.
string Openlabs.Mgcxm.Assets.FileAsset.ReadString()
Referenced by Openlabs.Mgcxm.Assets.FileFlagAsset.ReadFlag.
byte[] Openlabs.Mgcxm.Assets.FileAsset.ReadBytes()
void Openlabs.Mgcxm.Assets.FileAsset.WriteString(string data)
Referenced by Openlabs.Mgcxm.Assets.FileFlagAsset.ReadFlag, Openlabs.Mgcxm.Assets.DTOJsonFileAsset< TDtoType >.WriteDto, Openlabs.Mgcxm.Assets.FileFlagAsset.WriteFlag.
void Openlabs.Mgcxm.Assets.FileAsset.WriteBytes(byte[] data)
void Openlabs.Mgcxm.Assets.FileAsset.AppendString(string data)