Openlabs::Mgcxm::Net::MgcxmHttpResponse
bool Openlabs.Mgcxm.Net.MgcxmHttpResponse.IsSuccessStatusCode
Gets a value indicating whether the HTTP response status code indicates success (2xx).
bool Openlabs.Mgcxm.Net.MgcxmHttpResponse.IsErrorStatusCode
Gets a value indicating whether the HTTP response status code indicates an error (non-2xx).
HttpStatusCodes Openlabs.Mgcxm.Net.MgcxmHttpResponse.StatusCode
Gets the HTTP status code of the response.
string Openlabs.Mgcxm.Net.MgcxmHttpResponse.ErrorMessage
Gets the error message associated with the response.
string Openlabs.Mgcxm.Net.MgcxmHttpResponse.ContentType
Gets the content type of the response.
Dictionary<MgcxmString, MgcxmString> Openlabs.Mgcxm.Net.MgcxmHttpResponse.Headers
Gets the headers of the response.
byte [] Openlabs.Mgcxm.Net.MgcxmHttpResponse.ResponseData
Gets the response data as a byte array.
MgcxmId Openlabs.Mgcxm.Net.MgcxmHttpResponse.OwnerId
Gets the MgcxmId of the owner of the response.
HttpStatusCodes Openlabs.Mgcxm.Net.MgcxmHttpResponse._statusCode
string Openlabs.Mgcxm.Net.MgcxmHttpResponse._errorMessage
string Openlabs.Mgcxm.Net.MgcxmHttpResponse._contentType
Dictionary<MgcxmString, MgcxmString> Openlabs.Mgcxm.Net.MgcxmHttpResponse._headers
byte [] Openlabs.Mgcxm.Net.MgcxmHttpResponse._responseData
MgcxmId Openlabs.Mgcxm.Net.MgcxmHttpResponse._ownerId
static MgcxmHttpResponse Openlabs.Mgcxm.Net.MgcxmHttpResponse.New(HttpStatusCodes statusCode, string errorMessage, Dictionary< MgcxmString, MgcxmString > headers, byte[] response, MgcxmId owner)
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.Status(HttpStatusCodes statusCode)
Sets the HTTP status code of the response.
Referenced by Openlabs.Mgcxm.Tests.TestServer.HttpGet_Activities_CharadesV1_GetWords, Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV2_Get, Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV2_GetGifts, Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV2_Set, Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV3_GetItems, Openlabs.Mgcxm.Tests.TestServer.ConfigController.HttpGet_ConfigV2, Openlabs.Mgcxm.Tests.TestServer.MessagesController.HttpGet_MessagesV2_Get, Openlabs.Mgcxm.Tests.TestServer.PlayersController.HttpGet_PlayersV1_PlayerId, Openlabs.Mgcxm.Tests.TestServer.RelationshipsController.HttpGet_RelationshipsV2_Get, Openlabs.Mgcxm.Tests.TestServer.SettingsController.HttpGet_SettingsV2_Get, Openlabs.Mgcxm.Tests.TestServer.VersionCheckController.HttpGet_VersionCheckV1, Openlabs.Mgcxm.Tests.TestServer.PlatformLoginController.HttpPost_PlatformLoginV2.
int Openlabs.Mgcxm.Net.MgcxmHttpResponse.GetStatus()
Gets the HTTP status code of the response.
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.Header(string key, string value)
Sets a header in the response.
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content(HttpContentTypes contentType, byte[] data)
Sets the content of the response with a byte array and content type.
Referenced by Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content, Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content< T >, Openlabs.Mgcxm.Tests.TestWsServer.OnWebRequest.
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content(HttpContentTypes contentType, string data)
Sets the content of the response with a string data and content type.
References Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content.
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content< T >(T data)
Sets the content of the response by serializing an object to JSON and setting content type as JSON.
References Openlabs.Mgcxm.Net.MgcxmHttpResponse.Content.
IMgcxmHttpResponseModifiable Openlabs.Mgcxm.Net.MgcxmHttpResponse.File(string path)
Sets the content of the response from a file on disk.
async Task Openlabs.Mgcxm.Net.MgcxmHttpResponse.Transfer(HttpListenerResponse response)
Transfers the response to a HttpListenerResponse.
Referenced by Openlabs.Mgcxm.Common.Framework.OpenApiFramework.ResolveRequest.