JWT::JwtDecoder
readonly IJsonSerializer JWT.JwtDecoder._jsonSerializer
readonly IJwtValidator JWT.JwtDecoder._jwtValidator
readonly IBase64UrlEncoder JWT.JwtDecoder._urlEncoder
readonly IAlgorithmFactory JWT.JwtDecoder._algFactory
JWT.JwtDecoder.JwtDecoder(IJsonSerializer jsonSerializer, IBase64UrlEncoder urlEncoder)
Creates an instance of JwtDecoder
This overload supplies no IJwtValidator and no IAlgorithmFactory so the resulting decoder cannot be used for signature validation. jsonSerializer The JSON serializer urlEncoder The base64 URL encoder ArgumentNullException
JWT.JwtDecoder.JwtDecoder(IJsonSerializer jsonSerializer, IJwtValidator jwtValidator, IBase64UrlEncoder urlEncoder, IAlgorithmFactory algFactory)
Creates an instance of JwtDecoder
jsonSerializer The JSON serializer jwtValidator The JWT validator urlEncoder The base64 URL encoder algFactory The JWT algorithm Factory ArgumentNullException
JWT.JwtDecoder.JwtDecoder(IJsonSerializer jsonSerializer, IJwtValidator jwtValidator, IBase64UrlEncoder urlEncoder, IJwtAlgorithm algorithm)
Creates an instance of JwtDecoder
jsonSerializer The JSON serializer jwtValidator The JWT validator urlEncoder The base64 URL encoder algorithm The JWT algorithm ArgumentNullException
string JWT.JwtDecoder.DecodeHeader(string token)
Given a JWT, decodes it and return the header. token The JWT ArgumentException InvalidTokenPartsException FormatException
References JWT.JwtParts.Header.
T JWT.JwtDecoder.DecodeHeader< T >(JwtParts jwt)
Given a JWT, decodes it and return the header as an object. jwt The JWT ArgumentException ArgumentNullException FormatException
References JWT.JwtParts.Header.
string JWT.JwtDecoder.Decode(JwtParts jwt, bool verify)
Given a JWT, decodes it and return the payload. jwt The JWT verify Whether to verify the signature (default is true) A string containing the JSON payload ArgumentException ArgumentNullException ArgumentOutOfRangeException InvalidTokenPartsException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
Referenced by JWT.JwtDecoder.Decode, JWT.JwtDecoder.DecodeToObject, JWT.JwtDecoder.DecodeToObject, JWT.JwtDecoder.DecodeToObject.
string JWT.JwtDecoder.Decode(JwtParts jwt, byte[] key, bool verify)
Given a JWT, decodes it and return the payload. jwt The JWT key The key that were used to sign the JWT verify Whether to verify the signature (default is true) A string containing the JSON payload ArgumentException ArgumentNullException ArgumentOutOfRangeException InvalidTokenPartsException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
string JWT.JwtDecoder.Decode(JwtParts jwt, byte[][] keys, bool verify)
Given a JWT, decodes it and return the payload. jwt The JWT keys The keys provided which one of them was used to sign the JWT verify Whether to verify the signature (default is true) A string containing the JSON payload ArgumentException ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
References JWT.JwtDecoder.Decode, JWT.JwtDecoder.Validate.
object JWT.JwtDecoder.DecodeToObject(Type type, JwtParts jwt, bool verify)
Given a JWT, decodes it and return the payload as an object. type The type to deserialize to. jwt The JWT verify Whether to verify the signature (default is true) An object representing the payload ArgumentException ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
References JWT.JwtDecoder.Decode.
object JWT.JwtDecoder.DecodeToObject(Type type, JwtParts jwt, byte[] key, bool verify)
Given a JWT, decodes it and return the payload as an object. type The type to deserialize to. jwt The JWT key The key that was used to sign the JWT verify Whether to verify the signature (default is true) An object representing the payload ArgumentException ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
References JWT.JwtDecoder.Decode.
object JWT.JwtDecoder.DecodeToObject(Type type, JwtParts jwt, byte[][] keys, bool verify)
Given a JWT, decodes it and return the payload as an object. type The type to deserialize to. jwt The JWT keys The keys which one of them was used to sign the JWT verify Whether to verify the signature (default is true) An object representing the payload ArgumentException ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
References JWT.JwtDecoder.Decode.
void JWT.JwtDecoder.Validate(string[] parts, byte[] key)
Prepares data before calling IJwtValidator
parts The array representation of a JWT key The key that was used to sign the JWT ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
Referenced by JWT.JwtDecoder.Decode.
void JWT.JwtDecoder.Validate(string[] parts, params byte[][] keys)
Prepares data before calling IJwtValidator
parts The array representation of a JWT keys The keys provided which one of them was used to sign the JWT ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
void JWT.JwtDecoder.Validate(JwtParts jwt, params byte[][] keys)
Prepares data before calling IJwtValidator
jwt The JWT parts keys The keys provided which one of them was used to sign the JWT ArgumentException ArgumentNullException ArgumentOutOfRangeException FormatException SignatureVerificationException TokenNotYetValidException TokenExpiredException
References JWT.JwtDecoderContext.Create, JWT.JwtParts.Header, JWT.JwtParts.Payload, JWT.JwtParts.Signature.
string JWT.JwtDecoder.Decode(JwtParts jwt)
void JWT.JwtDecoder.ValidSymmetricAlgorithm(byte[][] keys, string decodedPayload, IJwtAlgorithm algorithm, byte[] bytesToSign, byte[] decodedSignature)
void JWT.JwtDecoder.ValidateNoneAlgorithm(JwtParts jwt)
static bool JWT.JwtDecoder.AllKeysHaveValues(byte[][] keys)