Openlabs::Mgcxm::Assets::DTOJsonFileAsset
virtual TDtoType Openlabs.Mgcxm.Assets.DTOJsonFileAsset< TDtoType >.ReadDto()
Referenced by Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV2_Get, Openlabs.Mgcxm.Tests.TestServer.SettingsController.HttpGet_SettingsV2_Get, Openlabs.Mgcxm.Tests.TestServer.SettingsController.HttpGet_SettingsV2_Set.
virtual void Openlabs.Mgcxm.Assets.DTOJsonFileAsset< TDtoType >.WriteDto(TDtoType dtoType)
References Openlabs.Mgcxm.Assets.FileAsset.WriteString.
Referenced by Openlabs.Mgcxm.Tests.TestServer.AvatarController.HttpGet_AvatarV2_Set, Openlabs.Mgcxm.Tests.TestServer.SettingsController.HttpGet_SettingsV2_Set.