JWT::IJwtDecoder
string JWT.IJwtDecoder.DecodeHeader(string token)
Given a JWT, decodes it and return the header.
token The JWT
Referenced by JWT.Builder.JwtBuilder.DecodeHeader, JWT.Builder.JwtBuilder.DecodeHeader< T >.
T JWT.IJwtDecoder.DecodeHeader< T >(JwtParts jwt)
Given a JWT, decodes it and return the header as an object.
jwt The JWT
string JWT.IJwtDecoder.Decode(JwtParts jwt, bool verify)
Given a JWT, decodes it and return the payload.
jwt The JWT verify Whether to verify the signature (default is true) A string containing the JSON payload
Referenced by JWT.Builder.JwtBuilder.Decode.
string JWT.IJwtDecoder.Decode(JwtParts jwt, byte[] key, bool verify)
Given a JWT, decodes it and return the payload.
jwt The JWT key The key that were used to sign the JWT verify Whether to verify the signature (default is true) A string containing the JSON payload
string JWT.IJwtDecoder.Decode(JwtParts jwt, byte[][] keys, bool verify)
Given a JWT, decodes it and return the payload.
jwt The JWT keys The keys provided which one of them was used to sign the JWT verify Whether to verify the signature (default is true) A string containing the JSON payload
object JWT.IJwtDecoder.DecodeToObject(Type type, JwtParts jwt, bool verify)
Given a JWT, decodes it and return the payload as an object.
type The type to deserialize to. jwt The JWT verify Whether to verify the signature (default is true) An object representing the payload
Referenced by JWT.Builder.JwtBuilder.Decode, JWT.Builder.JwtBuilder.Decode< T >.
object JWT.IJwtDecoder.DecodeToObject(Type type, JwtParts jwt, byte[] key, bool verify)
Given a JWT, decodes it and return the payload as an object.
type The type to deserialize to. jwt The JWT key The key that was used to sign the JWT verify Whether to verify the signature (default is true) An object representing the payload
object JWT.IJwtDecoder.DecodeToObject(Type type, JwtParts jwt, byte[][] keys, bool verify)
Given a JWT, decodes it and return the payload as an object.
type The type to deserialize to. jwt The JWT keys The keys which one of them was used to sign the JWT verify Whether to verify the signature (default is true) An object representing the payload